services:
  trabajo:
    build: .
    ports:
      - "8081:8081"
    networks:
      - red-trabajo
    environment:
      - SERVER_PORT=8081

  servicio-consumible:
    image: javillour/servicio-tt1:amd64
    networks:
      - red-trabajo

networks:
  red-trabajo:
    driver: bridge